export const roles = {
  SUPER_ADMIN: "Super Admin",
  HR_ADMIN: "HR Admin",
  REPORTING_MANAGER: "Reporting Manager",
  EMPLOYEE: "Employee",
  TRAINER: "Trainer",
  COMPLIANCE_OFFICER: "Compliance Officer",
};

export const moduleCatalog = [
  {
    key: "requisitions",
    label: "Requisitions",
    domain: "Pre-Hire",
    path: "/recruitment/requisitions",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER"],
    fields: ["title", "department", "openings", "hiringManager", "status", "targetJoiningDate"],
  },
  {
    key: "candidates",
    label: "Candidates",
    domain: "Pre-Hire",
    path: "/recruitment/candidates",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER"],
    fields: ["fullName", "email", "phone", "stage", "rating", "resumeUrl"],
  },
  {
    key: "interviews",
    label: "Interviews",
    domain: "Pre-Hire",
    path: "/recruitment/interviews",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER"],
    fields: ["candidateName", "round", "interviewer", "scheduledAt", "status", "score"],
  },
  {
    key: "offers",
    label: "Offers",
    domain: "Pre-Hire",
    path: "/recruitment/offers",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER"],
    writeRoles: ["HR_ADMIN"],
    fields: ["candidateName", "offeredCtc", "joiningDate", "status", "acceptedAt"],
  },
  {
    key: "onboardingTasks",
    label: "Onboarding Tasks",
    domain: "Onboarding",
    path: "/onboarding/tasks",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER"],
    fields: ["employeeName", "taskName", "taskType", "ownerRole", "dueDate", "status"],
  },
  {
    key: "employees",
    label: "Employee Master",
    domain: "Employee Management",
    path: "/employees",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN"],
    fields: ["employeeCode", "fullName", "department", "designation", "reportingManager", "location", "lifecycleStatus"],
  },
  {
    key: "documents",
    label: "Employee Documents",
    domain: "Employee Management",
    path: "/employees/documents",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE", "COMPLIANCE_OFFICER"],
    writeRoles: ["HR_ADMIN", "EMPLOYEE"],
    fields: ["employeeName", "documentType", "fileName", "expiryDate", "status"],
  },
  {
    key: "attendance",
    label: "Attendance Entries",
    domain: "Attendance",
    path: "/attendance/entries",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "EMPLOYEE"],
    fields: ["employeeName", "attendanceDate", "mode", "checkIn", "checkOut", "status"],
  },
  {
    key: "attendanceRegularizations",
    label: "Attendance Regularization",
    domain: "Attendance",
    path: "/attendance/regularizations",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    fields: ["employeeName", "attendanceDate", "reason", "status"],
  },
  {
    key: "leaveRequests",
    label: "Leave Requests",
    domain: "Leave",
    path: "/leave/requests",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    fields: ["employeeName", "leaveType", "fromDate", "toDate", "days", "status"],
  },
  {
    key: "leaveBalances",
    label: "Leave Balances",
    domain: "Leave",
    path: "/leave/balances",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN"],
    fields: ["employeeName", "leaveType", "balance", "asOfDate"],
  },
  {
    key: "holidays",
    label: "Holiday Calendar",
    domain: "Leave",
    path: "/leave/holidays",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN"],
    fields: ["location", "holidayDate", "name", "isOptional"],
  },
  {
    key: "compOffRequests",
    label: "Comp-Off",
    domain: "Comp-Off",
    path: "/comp-off/requests",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    fields: ["employeeName", "sourceWorkDate", "earnedDays", "expiresOn", "utilizedDays", "status"],
  },
  {
    key: "probationReviews",
    label: "Probation Reviews",
    domain: "Probation",
    path: "/probation/reviews",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER"],
    fields: ["employeeName", "reviewDay", "dueDate", "outcome", "status"],
  },
  {
    key: "performanceReviews",
    label: "Performance Reviews",
    domain: "Performance",
    path: "/performance/reviews",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    fields: ["employeeName", "cycle", "goal", "kpiScore", "status"],
  },
  {
    key: "trainings",
    label: "Training Calendar",
    domain: "Learning",
    path: "/learning/trainings",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE", "TRAINER"],
    writeRoles: ["HR_ADMIN", "TRAINER"],
    fields: ["title", "category", "audience", "trainingDate", "completionRate", "status"],
  },
  {
    key: "trainingAssignments",
    label: "Training Assignments",
    domain: "Learning",
    path: "/learning/assignments",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE", "TRAINER"],
    writeRoles: ["HR_ADMIN", "TRAINER"],
    fields: ["employeeName", "trainingTitle", "status", "completedAt"],
  },
  {
    key: "policies",
    label: "Policy Repository",
    domain: "Policy",
    path: "/policies",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "COMPLIANCE_OFFICER", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "COMPLIANCE_OFFICER"],
    fields: ["name", "category", "version", "effectiveDate", "reviewDate", "status"],
  },
  {
    key: "policyAcknowledgements",
    label: "Policy Acknowledgements",
    domain: "Policy",
    path: "/policies/acknowledgements",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "COMPLIANCE_OFFICER", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["EMPLOYEE", "HR_ADMIN"],
    fields: ["employeeName", "policyName", "version", "acknowledgedAt", "status"],
  },
  {
    key: "certifications",
    label: "Certification Management",
    domain: "Compliance",
    path: "/compliance/certifications",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "COMPLIANCE_OFFICER", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "COMPLIANCE_OFFICER", "EMPLOYEE"],
    fields: ["employeeName", "certificationName", "issuer", "issuedOn", "expiresOn", "status"],
  },
  {
    key: "complianceTasks",
    label: "Compliance Tasks",
    domain: "Compliance",
    path: "/compliance/tasks",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "COMPLIANCE_OFFICER"],
    writeRoles: ["HR_ADMIN", "COMPLIANCE_OFFICER"],
    fields: ["title", "complianceType", "owner", "dueDate", "status"],
  },
  {
    key: "exitCases",
    label: "Exit Management",
    domain: "Exit",
    path: "/exits/resignations",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE"],
    fields: ["employeeName", "resignationDate", "lastWorkingDay", "noticeDays", "status"],
  },
  {
    key: "exitChecklists",
    label: "Exit Checklist",
    domain: "Exit",
    path: "/exits/checklists",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER"],
    writeRoles: ["HR_ADMIN", "REPORTING_MANAGER"],
    fields: ["employeeName", "itemName", "ownerRole", "dueDate", "status"],
  },
  {
    key: "notifications",
    label: "Notifications",
    domain: "System",
    path: "/notifications",
    readRoles: ["SUPER_ADMIN", "HR_ADMIN", "REPORTING_MANAGER", "EMPLOYEE", "TRAINER", "COMPLIANCE_OFFICER"],
    writeRoles: ["SUPER_ADMIN", "HR_ADMIN"],
    fields: ["title", "body", "readAt", "createdAt"],
  },
];

export function moduleByPath(path) {
  return moduleCatalog.find((module) => module.path === path);
}

export function moduleByKey(key) {
  return moduleCatalog.find((module) => module.key === key);
}
